VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/fedora-20"
  config.vm.provision :shell, :path => "fixtty.sh", :privileged => true
  config.vm.provision :shell, :path => "install-1.sh", :privileged => false
end
