VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-7.0"

  # Disable /vagrant - not needed and expensive rsync with AWS
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :aws do |aws, override|
    # Use a dummy box and specify everything here in Vagrantfile
    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    # Ensure tty is not required to run sudo
    aws.user_data = <<-eos
      #cloud-config
      runcmd:
        - echo 'Defaults:centos !requiretty' > /etc/sudoers.d/888-vagrant-cloud-init-requiretty
    eos

    # AWS API credentials
    aws.access_key_id = ENV["AWS_ACCESS_ID"]
    aws.secret_access_key = ENV["AWS_ACCESS_KEY"]

    # Instance login key - name in AWS and path to local PEM file
    aws.keypair_name = ENV["AWS_KEYPAIR_NAME"]
    override.ssh.private_key_path = ENV["AWS_KEYPAIR_KEY_FILE"]

    # AWS machine description
    aws.region = "us-west-2"
    aws.instance_type = "m3.medium"
    aws.security_groups = [ENV["AWS_SECURITY_GROUP"]]

    aws.ami = "ami-c7d092f7"  # CentOS 7 x86_64 (2014_09_29)
    override.ssh.username = "centos"
    aws.tags = {"Name" => "Flocker CLI (CentOS)"}
  end

  config.vm.provision :shell, :path => "install-1.sh", :privileged => false
end
